baseurl = "https://lentink.consulting/"
title = "Lentink.consulting"
author = "Sander Lentink"
defaultContentLanguage = "en"
language = "en-US"
theme = "hugoscroll"

[Params]
  github = "svlentink"
#  bitbucket = "floch"
#  twitter = "svlentink"
#  email = "sv@lent.ink"
  description = "Freelance DevOps / Linux Engineer"
  linkedin = "svlentink"
  cover = "/img/penguin-container.jpg"
#  logo = "/img/logo-1.jpg"

